/**
  @Company
    Microchip Technology Inc.

  @File Name
    drv_usersetup_TPBLPFC.h

  @Summary
    This is the generated driver implementation file using PIC24 / dsPIC33 / PIC32MM MCUs

  @Description
    This source file provides all the function for the power controller to control and drive the power stage(s).
    Generation Information :
        Product Revision  :  PIC24 / dsPIC33 / PIC32MM MCUs - 1.167.0
        Device            :  dsPIC33CH512MP506S1      
    The generated drivers are tested against the following:
        Compiler          :  XC16 v1.70
        MPLAB 	          :  MPLAB X v6.00
*/

/*
    (c) 2022 Microchip Technology Inc. and its subsidiaries. You may use this
    software and any derivatives exclusively with Microchip products.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION
    WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

    MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
    TERMS.
*/

#ifndef DRV_USERSETUP_TPBLPFC_H
#define	DRV_USERSETUP_TPBLPFC_H

#define PH1_PWM 1
#define PH2_PWM 2
#define PH3_PWM 3

/*******************************************************************************
 * @fn          #ifdefs for mode settings    
 * @brief       settings coming from Totem-Pole PFC Solution Configuration
 * @details     #ifdefs generated by GUI si copied to clipboard
 *              paste the clipboard
 *              
 *******************************************************************************/

// 09/12/2022 11:42:40
// Three Phase 
#define High_Voltage 0
//<< CHECK CURRENT LOOP Pole#0 
#undef SinglePhase1 
#undef DualPhase1_3 
#define ThreePhase 
#define ACVin 
#define OuterVloop 
#undef Reverse 
#define ClosedLoop 
#undef dffMode 
#undef AutoOn 
#define  ModeDeadTime 320  //80ns 
#define VoutRef 2792  //75 V
#define IinOC 930  //30 A
#define VoutOV 3351  //90 V
#define CCMCurrent 62  //2.0 A
#define CANSendID 0x202
#define CANReceiveID 0x203

/*******************************************************************************
 * @fn          open loop startup after ZC    
 * @brief       
 * @details     in function SoftstartAfterZC_PHx are the settings for the
 *              open loop startup used
 *              
 *******************************************************************************/

#ifdef ThreePhase
    #define OLStartupPulses 3
    #define OLPWMCounterShift 11
//    #define OLStartupPulses 19
//    #define OLPWMCounterShift 9
//    #define OLStartupPulses 10
//    #define OLPWMCounterShift 11
#else
    #define OLStartupPulses 10
    #define OLPWMCounterShift 11
#endif

//==============================================================================
//==============================================================================

#endif	/* DRV_USERSETUP_TPBLPFC_H */

